# Generated by Django 5.0.6 on 2024-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_action",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="последнее сообщение"
            ),
        ),
    ]
